[workspace]

members = [
    "minimal",
    "in-memory",
    "sqlite",
    "cookies",
    "login",
    "authorization",
    "integration",
    "integration/integration-lib",
    "tls",
    "tls/tls-lib",
    "cleanup",
    "cleanup/cleanup-lib",
]