@baseUrl = http://127.0.0.1:8080

# @name create
POST {{baseUrl}}/todos HTTP/1.1
content-type: application/json

{
    "task": "Task from request another one",
    "details": "Some details from the request wow"
}

####

# @name delete
POST {{baseUrl}}/todos/4 HTTP/1.1

####

# @name index
GET {{baseUrl}}/ HTTP/1.1

####

# @name get_todos
GET {{baseUrl}}/todos HTTP/1.1
