@baseUrl = http://127.0.0.1:8080

# @name insert_user
POST {{baseUrl}}/users HTTP/1.1
Authorization: Basic username:password
Content-Type: application/json

{
    "valid_username": "user",
    "valid_password": "plaintext"
}

####

# @name insert_task
POST {{baseUrl}}/tasks HTTP/1.1
Authorization: Basic user:plaintext
Content-Type: application/json

{
    "non_empty_title": "Todo",
    "details": "Some details"
}

####

# @name login
POST {{baseUrl}}/users/login HTTP/1.1
Authorization: Basic user:plaintext
Content-Type: application/json

{
    "username": "user",
    "password": "plaintext"
}

####

# @name logout
POST {{baseUrl}}/users/logout HTTP/1.1

####

# @name find
GET {{baseUrl}}/tasks HTTP/1.1
Authorization: Basic username:password

