@baseUrl = http://127.0.0.1:8080

# @name register_user
POST {{baseUrl}}/users/register HTTP/1.1
Authorization: Basic user:user
Content-Type: application/json

{
    "valid_username": "user",
    "valid_password": "plaintext"
}

####

# @name insert_invalid_user_username
POST {{baseUrl}}/users HTTP/1.1
Authorization: Basic user:user
Content-Type: application/json

{
    "valid_username": "",
    "valid_password": "plaintext"
}

####

# @name insert_invalid_empty_user_password
POST {{baseUrl}}/users HTTP/1.1
Authorization: Basic user:user
Content-Type: application/json

{
    "valid_username": "user",
    "valid_password": ""
}
