@baseUrl = http://127.0.0.1:8080


# @name login
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "plaintext"
}

####

# @name logout
POST {{baseUrl}}/users/logout HTTP/1.1
