@baseUrl = http://127.0.0.1:8080

# @name get_index
GET {{baseUrl}} HTTP/1.1

####

# @name create_database
POST {{baseUrl}}/database HTTP/1.1

####

# @name insert_task
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "non_empty_title": "Todo",
    "details": "Some details"
}

####

# @name insert_invalid_task_title
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "non_empty_title": "",
    "details": "Some details"
}

####

# @name insert_empty_task_details
POST {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "non_empty_title": "Todo",
    "details": ""
}

####

# @name update_task
PUT {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "new_title": "Todo Updated",
    "details": "Some details Updated"
}

####

# @name update_invalid_task_title
PUT {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "new_title": "",
    "details": "Some details Updated"
}

####

# @name update_empty_task_details
PUT {{baseUrl}}/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "new_title": "Todo Updated",
    "details": ""
}

####

# @name delete
DELETE  {{baseUrl}}/tasks/1 HTTP/1.1

####

# @name find_all
GET {{baseUrl}}/tasks HTTP/1.1

####

# @name find_by_id
GET {{baseUrl}}/tasks/1 HTTP/1.1

####