@baseUrl = http://127.0.0.1:8080

# @name insert_task
POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "non_empty_title": "Todo",
    "details": "Some details"
}

####

# @name insert_invalid_task_title
POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "non_empty_title": "",
    "details": "Some details"
}

####

# @name insert_empty_task_details
POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "non_empty_title": "Todo",
    "details": ""
}
