@baseUrl = http://127.0.0.1:8080

# @name update_task
PUT {{baseUrl}}/tasks
Content-Type: application/json

{
    "id": 1,
    "new_title": "Todo Updated",
    "details": "Some details Updated"
}

####

# @name update_invalid_task_title
PUT {{baseUrl}}/tasks
Content-Type: application/json

{
    "id": 1,
    "new_title": "",
    "details": "Some details Updated"
}

####

# @name update_empty_task_details
PUT {{baseUrl}}/tasks
Content-Type: application/json

{
    "id": 1,
    "new_title": "Todo Updated",
    "details": ""
}

####

