@baseUrl = http://127.0.0.1:8080

# @name check_user
GET {{baseUrl}}/user HTTP/1.1

####

# @name login
POST {{baseUrl}}/user/login HTTP/1.1

####

# @name logout
POST {{baseUrl}}/user/logout HTTP/1.1
